title: MetaGEAR
description: MetaGEAR - High-throughput microbiome metagenomic analysis platform

# GitHub Pages settings
plugins:
  - jekyll-readme-index
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-relative-links

# Default layout for pages
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Markdown settings
markdown: kramdown
highlighter: rouge
